"""
Configuration and CURRENT Nifty Midcap 150 Stock List
Updated: April 2026
"""

CONFIG = {
    "CAPITAL": 200000,
    "MAX_LEGS": 5,
    "PER_LEG_PCT": 0.20,
    "HARD_SL_PCT": 0.06,
    "VOLUME_MULTIPLIER": 1.5,
}

STOCK_LIST = [
    {"symbol": "3MINDIA", "name": "3M India", "sector": "Diversified"},
    {"symbol": "360ONE", "name": "360 ONE WAM", "sector": "Financial"},
    {"symbol": "ABBOTINDIA", "name": "Abbott India", "sector": "Pharma"},
    {"symbol": "ABCAPITAL", "name": "Aditya Birla Capital", "sector": "Financial"},
    {"symbol": "ACC", "name": "ACC Ltd", "sector": "Cement"},
    {"symbol": "AIAENG", "name": "AIA Engineering", "sector": "Capital Goods"},
    {"symbol": "AIIL", "name": "Authum Investment & Infra", "sector": "Financial"},
    {"symbol": "AJANTPHARM", "name": "Ajanta Pharma", "sector": "Pharma"},
    {"symbol": "ALKEM", "name": "Alkem Laboratories", "sector": "Pharma"},
    {"symbol": "ANTHEM", "name": "Anthem Biosciences", "sector": "Pharma"},
    {"symbol": "APARINDS", "name": "Apar Industries", "sector": "Capital Goods"},
    {"symbol": "APLAPOLLO", "name": "APL Apollo Tubes", "sector": "Metals"},
    {"symbol": "APOLLOTYRE", "name": "Apollo Tyres", "sector": "Auto"},
    {"symbol": "ASHOKLEY", "name": "Ashok Leyland", "sector": "Auto"},
    {"symbol": "ASTRAL", "name": "Astral Ltd", "sector": "Building Materials"},
    {"symbol": "ATGL", "name": "Adani Total Gas", "sector": "Energy"},
    {"symbol": "AUBANK", "name": "AU Small Finance Bank", "sector": "Banking"},
    {"symbol": "AUROPHARMA", "name": "Aurobindo Pharma", "sector": "Pharma"},
    {"symbol": "AWL", "name": "Adani Wilmar", "sector": "FMCG"},
    {"symbol": "BAJAJHFL", "name": "Bajaj Housing Finance", "sector": "Financial"},
    {"symbol": "BALKRISIND", "name": "Balkrishna Industries", "sector": "Auto"},
    {"symbol": "BANKINDIA", "name": "Bank of India", "sector": "Banking"},
    {"symbol": "BDL", "name": "Bharat Dynamics", "sector": "Defence"},
    {"symbol": "BERGEPAINT", "name": "Berger Paints", "sector": "Chemicals"},
    {"symbol": "BHARATFORG", "name": "Bharat Forge", "sector": "Auto"},
    {"symbol": "BHARTIHEXA", "name": "Bharti Hexacom", "sector": "Telecom"},
    {"symbol": "BHEL", "name": "BHEL", "sector": "Capital Goods"},
    {"symbol": "BIOCON", "name": "Biocon", "sector": "Pharma"},
    {"symbol": "BLUESTARCO", "name": "Blue Star", "sector": "Consumer Durables"},
    {"symbol": "BSE", "name": "BSE Ltd", "sector": "Financial"},
    {"symbol": "COCHINSHIP", "name": "Cochin Shipyard", "sector": "Defence"},
    {"symbol": "COFORGE", "name": "Coforge", "sector": "IT"},
    {"symbol": "COLPAL", "name": "Colgate Palmolive", "sector": "FMCG"},
    {"symbol": "CONCOR", "name": "Container Corp", "sector": "Logistics"},
    {"symbol": "COROMANDEL", "name": "Coromandel International", "sector": "Chemicals"},
    {"symbol": "CRISIL", "name": "CRISIL Ltd", "sector": "Financial"},
    {"symbol": "DABUR", "name": "Dabur India", "sector": "FMCG"},
    {"symbol": "DALBHARAT", "name": "Dalmia Bharat", "sector": "Cement"},
    {"symbol": "DIXON", "name": "Dixon Technologies", "sector": "Electronics"},
    {"symbol": "ENDURANCE", "name": "Endurance Technologies", "sector": "Auto"},
    {"symbol": "ESCORTS", "name": "Escorts Kubota", "sector": "Auto"},
    {"symbol": "EXIDEIND", "name": "Exide Industries", "sector": "Auto"},
    {"symbol": "FEDERALBNK", "name": "Federal Bank", "sector": "Banking"},
    {"symbol": "FLUOROCHEM", "name": "Gujarat Fluorochemicals", "sector": "Chemicals"},
    {"symbol": "FORTIS", "name": "Fortis Healthcare", "sector": "Healthcare"},
    {"symbol": "GICRE", "name": "General Insurance Corp", "sector": "Insurance"},
    {"symbol": "GLAXO", "name": "GlaxoSmithKline Pharma", "sector": "Pharma"},
    {"symbol": "GLENMARK", "name": "Glenmark Pharma", "sector": "Pharma"},
    {"symbol": "GMRAIRPORT", "name": "GMR Airports Infra", "sector": "Infrastructure"},
    {"symbol": "GODREJIND", "name": "Godrej Industries", "sector": "Diversified"},
    {"symbol": "GODREJPROP", "name": "Godrej Properties", "sector": "Realty"},
    {"symbol": "GODFRYPHLP", "name": "Godfrey Phillips India", "sector": "FMCG"},
    {"symbol": "GROWW", "name": "Groww", "sector": "Financial"},
    {"symbol": "GVT&D", "name": "GE Vernova T&D India", "sector": "Capital Goods"},
    {"symbol": "HAVELLS", "name": "Havells India", "sector": "Consumer Durables"},
    {"symbol": "HDBFS", "name": "HDB Financial Services", "sector": "Financial"},
    {"symbol": "HEROMOTOCO", "name": "Hero MotoCorp", "sector": "Auto"},
    {"symbol": "HEXT", "name": "Hexaware Technologies", "sector": "IT"},
    {"symbol": "HINDPETRO", "name": "HPCL", "sector": "Energy"},
    {"symbol": "HONAUT", "name": "Honeywell Automation", "sector": "Capital Goods"},
    {"symbol": "HUDCO", "name": "HUDCO", "sector": "Financial"},
    {"symbol": "ICICIAMC", "name": "ICICI Prudential AMC", "sector": "Financial"},
    {"symbol": "ICICIGI", "name": "ICICI Lombard", "sector": "Insurance"},
    {"symbol": "ICICIPRULI", "name": "ICICI Pru Life Insurance", "sector": "Insurance"},
    {"symbol": "IDEA", "name": "Vodafone Idea", "sector": "Telecom"},
    {"symbol": "IDFCFIRSTB", "name": "IDFC First Bank", "sector": "Banking"},
    {"symbol": "INDIANB", "name": "Indian Bank", "sector": "Banking"},
    {"symbol": "INDUSINDBK", "name": "IndusInd Bank", "sector": "Banking"},
    {"symbol": "INDUSTOWER", "name": "Indus Towers", "sector": "Telecom"},
    {"symbol": "IPCALAB", "name": "IPCA Laboratories", "sector": "Pharma"},
    {"symbol": "IRCTC", "name": "IRCTC", "sector": "Travel"},
    {"symbol": "IREDA", "name": "Indian Renewable Energy", "sector": "Financial"},
    {"symbol": "ITCHOTELS", "name": "ITC Hotels", "sector": "Hotels"},
    {"symbol": "JKCEMENT", "name": "JK Cement", "sector": "Cement"},
    {"symbol": "JSL", "name": "Jindal Stainless", "sector": "Metals"},
    {"symbol": "JSWENERGY", "name": "JSW Energy", "sector": "Energy"},
    {"symbol": "JSWINFRA", "name": "JSW Infrastructure", "sector": "Infrastructure"},
    {"symbol": "JUBLFOOD", "name": "Jubilant FoodWorks", "sector": "Consumer"},
    {"symbol": "KALYANKJIL", "name": "Kalyan Jewellers", "sector": "Consumer"},
    {"symbol": "KEI", "name": "KEI Industries", "sector": "Capital Goods"},
    {"symbol": "KPITTECH", "name": "KPIT Technologies", "sector": "IT"},
    {"symbol": "KPRMILL", "name": "KPR Mill", "sector": "Textiles"},
    {"symbol": "LAURUSLABS", "name": "Laurus Labs", "sector": "Pharma"},
    {"symbol": "LENSKART", "name": "Lenskart", "sector": "Consumer"},
    {"symbol": "LGEINDIA", "name": "LG Electronics India", "sector": "Consumer Durables"},
    {"symbol": "LICHSGFIN", "name": "LIC Housing Finance", "sector": "Financial"},
    {"symbol": "LICI", "name": "LIC of India", "sector": "Insurance"},
    {"symbol": "LINDEINDIA", "name": "Linde India", "sector": "Chemicals"},
    {"symbol": "LLOYDSME", "name": "Lloyds Metals", "sector": "Metals"},
    {"symbol": "LTF", "name": "L&T Finance", "sector": "Financial"},
    {"symbol": "LTTS", "name": "L&T Technology Services", "sector": "IT"},
    {"symbol": "LUPIN", "name": "Lupin", "sector": "Pharma"},
    {"symbol": "M&MFIN", "name": "Mahindra Finance", "sector": "Financial"},
    {"symbol": "MAHABANK", "name": "Bank of Maharashtra", "sector": "Banking"},
    {"symbol": "MANKIND", "name": "Mankind Pharma", "sector": "Pharma"},
    {"symbol": "MARICO", "name": "Marico", "sector": "FMCG"},
    {"symbol": "MCX", "name": "Multi Commodity Exchange", "sector": "Financial"},
    {"symbol": "MEDANTA", "name": "Global Health Medanta", "sector": "Healthcare"},
    {"symbol": "MFSL", "name": "Max Financial Services", "sector": "Financial"},
    {"symbol": "MOTILALOFS", "name": "Motilal Oswal Financial", "sector": "Financial"},
    {"symbol": "MPHASIS", "name": "Mphasis", "sector": "IT"},
    {"symbol": "MRF", "name": "MRF Ltd", "sector": "Auto"},
    {"symbol": "NAM-INDIA", "name": "Nippon Life India AMC", "sector": "Financial"},
    {"symbol": "NATIONALUM", "name": "National Aluminium", "sector": "Metals"},
    {"symbol": "NAUKRI", "name": "Info Edge Naukri", "sector": "IT"},
    {"symbol": "NHPC", "name": "NHPC", "sector": "Energy"},
    {"symbol": "NIACL", "name": "New India Assurance", "sector": "Insurance"},
    {"symbol": "NLCINDIA", "name": "NLC India", "sector": "Energy"},
    {"symbol": "NMDC", "name": "NMDC", "sector": "Metals"},
    {"symbol": "NTPCGREEN", "name": "NTPC Green Energy", "sector": "Energy"},
    {"symbol": "NYKAA", "name": "FSN E-Commerce Nykaa", "sector": "Consumer"},
    {"symbol": "OBEROIRLTY", "name": "Oberoi Realty", "sector": "Realty"},
    {"symbol": "OFSS", "name": "Oracle Financial Services", "sector": "IT"},
    {"symbol": "OIL", "name": "Oil India", "sector": "Energy"},
    {"symbol": "PAGEIND", "name": "Page Industries", "sector": "Consumer"},
    {"symbol": "PATANJALI", "name": "Patanjali Foods", "sector": "FMCG"},
    {"symbol": "PAYTM", "name": "One97 Communications", "sector": "Fintech"},
    {"symbol": "PERSISTENT", "name": "Persistent Systems", "sector": "IT"},
    {"symbol": "PETRONET", "name": "Petronet LNG", "sector": "Energy"},
    {"symbol": "PHOENIXLTD", "name": "Phoenix Mills", "sector": "Realty"},
    {"symbol": "PIIND", "name": "PI Industries", "sector": "Chemicals"},
    {"symbol": "POLICYBZR", "name": "PB Fintech PolicyBazaar", "sector": "Fintech"},
    {"symbol": "POLYCAB", "name": "Polycab India", "sector": "Capital Goods"},
    {"symbol": "POWERINDIA", "name": "Hitachi Energy India", "sector": "Capital Goods"},
    {"symbol": "PREMIERENE", "name": "Premier Energies", "sector": "Energy"},
    {"symbol": "PRESTIGE", "name": "Prestige Estates", "sector": "Realty"},
    {"symbol": "RADICO", "name": "Radico Khaitan", "sector": "Consumer"},
    {"symbol": "RVNL", "name": "Rail Vikas Nigam", "sector": "Infrastructure"},
    {"symbol": "SAIL", "name": "SAIL", "sector": "Metals"},
    {"symbol": "SBICARD", "name": "SBI Cards", "sector": "Financial"},
    {"symbol": "SCHAEFFLER", "name": "Schaeffler India", "sector": "Auto"},
    {"symbol": "SJVN", "name": "SJVN", "sector": "Energy"},
    {"symbol": "SRF", "name": "SRF Ltd", "sector": "Chemicals"},
    {"symbol": "SUNDARMFIN", "name": "Sundaram Finance", "sector": "Financial"},
    {"symbol": "SUPREMEIND", "name": "Supreme Industries", "sector": "Building Materials"},
    {"symbol": "SUZLON", "name": "Suzlon Energy", "sector": "Energy"},
    {"symbol": "SWIGGY", "name": "Swiggy", "sector": "Consumer Tech"},
    {"symbol": "TATACOMM", "name": "Tata Communications", "sector": "Telecom"},
    {"symbol": "TATAELXSI", "name": "Tata Elxsi", "sector": "IT"},
    {"symbol": "TATAINVEST", "name": "Tata Investment Corp", "sector": "Financial"},
    {"symbol": "THERMAX", "name": "Thermax", "sector": "Capital Goods"},
    {"symbol": "TIINDIA", "name": "Tube Investments", "sector": "Auto"},
    {"symbol": "TORNTPOWER", "name": "Torrent Power", "sector": "Energy"},
    {"symbol": "UBL", "name": "United Breweries", "sector": "Consumer"},
    {"symbol": "UNOMINDA", "name": "UNO Minda", "sector": "Auto"},
    {"symbol": "UPL", "name": "UPL Ltd", "sector": "Chemicals"},
    {"symbol": "VMM", "name": "Vishal Mega Mart", "sector": "Retail"},
    {"symbol": "VOLTAS", "name": "Voltas", "sector": "Consumer Durables"},
    {"symbol": "WAAREEENER", "name": "Waaree Energies", "sector": "Energy"},
    {"symbol": "YESBANK", "name": "Yes Bank", "sector": "Banking"},
]

SECTORS = sorted(list(set(s["sector"] for s in STOCK_LIST)))

NSE_HOLIDAYS_2025 = [
    "2025-01-26", "2025-02-26", "2025-03-14", "2025-03-31",
    "2025-04-10", "2025-04-14", "2025-04-18", "2025-05-01",
    "2025-06-07", "2025-07-06", "2025-08-15", "2025-08-16",
    "2025-09-05", "2025-10-02", "2025-10-20", "2025-10-21",
    "2025-11-05", "2025-11-26", "2025-12-25",
]
