"""
Configuration and Nifty Midcap 150 Stock List
"""

CONFIG = {
    "CAPITAL": 200000,
    "MAX_LEGS": 5,
    "PER_LEG_PCT": 0.20,
    "HARD_SL_PCT": 0.06,
    "VOLUME_MULTIPLIER": 1.5,
    "SMA_PERIOD": 50,
    "HIGH_PERIOD": 50,
    "LOW_PERIOD": 50,
    "VOLUME_AVG_PERIOD": 20,
}

# Complete Nifty Midcap 150 List
STOCK_LIST = [
    {"symbol": "AARTIIND", "name": "Aarti Industries", "sector": "Chemicals"},
    {"symbol": "ABB", "name": "ABB India", "sector": "Capital Goods"},
    {"symbol": "ABFRL", "name": "Aditya Birla Fashion", "sector": "Consumer"},
    {"symbol": "ACC", "name": "ACC Ltd", "sector": "Cement"},
    {"symbol": "AIAENG", "name": "AIA Engineering", "sector": "Capital Goods"},
    {"symbol": "AJANTPHARM", "name": "Ajanta Pharma", "sector": "Pharma"},
    {"symbol": "ALKEM", "name": "Alkem Laboratories", "sector": "Pharma"},
    {"symbol": "ANGELONE", "name": "Angel One", "sector": "Financial"},
    {"symbol": "APLAPOLLO", "name": "APL Apollo Tubes", "sector": "Metals"},
    {"symbol": "ASHOKLEY", "name": "Ashok Leyland", "sector": "Auto"},
    {"symbol": "ASTRAL", "name": "Astral Ltd", "sector": "Building Materials"},
    {"symbol": "ATUL", "name": "Atul Ltd", "sector": "Chemicals"},
    {"symbol": "AUBANK", "name": "AU Small Finance Bank", "sector": "Banking"},
    {"symbol": "AUROPHARMA", "name": "Aurobindo Pharma", "sector": "Pharma"},
    {"symbol": "BALKRISIND", "name": "Balkrishna Industries", "sector": "Auto"},
    {"symbol": "BANDHANBNK", "name": "Bandhan Bank", "sector": "Banking"},
    {"symbol": "BATAINDIA", "name": "Bata India", "sector": "Consumer"},
    {"symbol": "BDL", "name": "Bharat Dynamics", "sector": "Defence"},
    {"symbol": "BEL", "name": "Bharat Electronics", "sector": "Defence"},
    {"symbol": "BHARATFORG", "name": "Bharat Forge", "sector": "Auto"},
    {"symbol": "BHEL", "name": "BHEL", "sector": "Capital Goods"},
    {"symbol": "BIOCON", "name": "Biocon", "sector": "Pharma"},
    {"symbol": "BRIGADE", "name": "Brigade Enterprises", "sector": "Realty"},
    {"symbol": "BSE", "name": "BSE Ltd", "sector": "Financial"},
    {"symbol": "CAMS", "name": "CAMS", "sector": "Financial"},
    {"symbol": "CANFINHOME", "name": "Can Fin Homes", "sector": "Financial"},
    {"symbol": "CARBORUNIV", "name": "Carborundum Universal", "sector": "Capital Goods"},
    {"symbol": "CDSL", "name": "CDSL", "sector": "Financial"},
    {"symbol": "CGPOWER", "name": "CG Power", "sector": "Capital Goods"},
    {"symbol": "CHAMBLFERT", "name": "Chambal Fertilisers", "sector": "Chemicals"},
    {"symbol": "COFORGE", "name": "Coforge", "sector": "IT"},
    {"symbol": "COLPAL", "name": "Colgate Palmolive", "sector": "FMCG"},
    {"symbol": "CONCOR", "name": "Container Corp", "sector": "Logistics"},
    {"symbol": "COROMANDEL", "name": "Coromandel International", "sector": "Chemicals"},
    {"symbol": "CROMPTON", "name": "Crompton Greaves CE", "sector": "Consumer"},
    {"symbol": "CUMMINSIND", "name": "Cummins India", "sector": "Capital Goods"},
    {"symbol": "CYIENT", "name": "Cyient", "sector": "IT"},
    {"symbol": "DALBHARAT", "name": "Dalmia Bharat", "sector": "Cement"},
    {"symbol": "DEEPAKNTR", "name": "Deepak Nitrite", "sector": "Chemicals"},
    {"symbol": "DELHIVERY", "name": "Delhivery", "sector": "Logistics"},
    {"symbol": "DEVYANI", "name": "Devyani International", "sector": "Consumer"},
    {"symbol": "DIXON", "name": "Dixon Technologies", "sector": "Electronics"},
    {"symbol": "EMAMILTD", "name": "Emami", "sector": "FMCG"},
    {"symbol": "ENDURANCE", "name": "Endurance Technologies", "sector": "Auto"},
    {"symbol": "ESCORTS", "name": "Escorts Kubota", "sector": "Auto"},
    {"symbol": "EXIDEIND", "name": "Exide Industries", "sector": "Auto"},
    {"symbol": "FEDERALBNK", "name": "Federal Bank", "sector": "Banking"},
    {"symbol": "FACT", "name": "Fertilisers and Chemicals", "sector": "Chemicals"},
    {"symbol": "FINEORG", "name": "Fine Organic", "sector": "Chemicals"},
    {"symbol": "FORTIS", "name": "Fortis Healthcare", "sector": "Healthcare"},
    {"symbol": "GLENMARK", "name": "Glenmark Pharma", "sector": "Pharma"},
    {"symbol": "GLAXO", "name": "GlaxoSmithKline Pharma", "sector": "Pharma"},
    {"symbol": "GNFC", "name": "GNFC", "sector": "Chemicals"},
    {"symbol": "GODREJCP", "name": "Godrej Consumer", "sector": "FMCG"},
    {"symbol": "GODREJPROP", "name": "Godrej Properties", "sector": "Realty"},
    {"symbol": "GRANULES", "name": "Granules India", "sector": "Pharma"},
    {"symbol": "GRINDWELL", "name": "Grindwell Norton", "sector": "Capital Goods"},
    {"symbol": "GSPL", "name": "Gujarat State Petronet", "sector": "Energy"},
    {"symbol": "GUJGASLTD", "name": "Gujarat Gas", "sector": "Energy"},
    {"symbol": "HAL", "name": "Hindustan Aeronautics", "sector": "Defence"},
    {"symbol": "HDFCAMC", "name": "HDFC AMC", "sector": "Financial"},
    {"symbol": "HINDPETRO", "name": "HPCL", "sector": "Energy"},
    {"symbol": "HONAUT", "name": "Honeywell Automation", "sector": "Capital Goods"},
    {"symbol": "HUDCO", "name": "HUDCO", "sector": "Financial"},
    {"symbol": "IDFCFIRSTB", "name": "IDFC First Bank", "sector": "Banking"},
    {"symbol": "IEX", "name": "Indian Energy Exchange", "sector": "Energy"},
    {"symbol": "IIFL", "name": "IIFL Finance", "sector": "Financial"},
    {"symbol": "INDHOTEL", "name": "Indian Hotels", "sector": "Hotels"},
    {"symbol": "INDIANB", "name": "Indian Bank", "sector": "Banking"},
    {"symbol": "INDIAMART", "name": "IndiaMART", "sector": "IT"},
    {"symbol": "INDUSTOWER", "name": "Indus Towers", "sector": "Telecom"},
    {"symbol": "IRCTC", "name": "IRCTC", "sector": "Travel"},
    {"symbol": "IRB", "name": "IRB Infrastructure", "sector": "Infrastructure"},
    {"symbol": "IGL", "name": "Indraprastha Gas", "sector": "Energy"},
    {"symbol": "JKCEMENT", "name": "JK Cement", "sector": "Cement"},
    {"symbol": "JSWENERGY", "name": "JSW Energy", "sector": "Energy"},
    {"symbol": "JUBLFOOD", "name": "Jubilant FoodWorks", "sector": "Consumer"},
    {"symbol": "KAJARIACER", "name": "Kajaria Ceramics", "sector": "Building Materials"},
    {"symbol": "KANSAINER", "name": "Kansai Nerolac", "sector": "Chemicals"},
    {"symbol": "KEI", "name": "KEI Industries", "sector": "Capital Goods"},
    {"symbol": "KPITTECH", "name": "KPIT Technologies", "sector": "IT"},
    {"symbol": "LTFH", "name": "L&T Finance", "sector": "Financial"},
    {"symbol": "LALPATHLAB", "name": "Dr Lal PathLabs", "sector": "Healthcare"},
    {"symbol": "LATENTVIEW", "name": "Latent View Analytics", "sector": "IT"},
    {"symbol": "LAURUSLABS", "name": "Laurus Labs", "sector": "Pharma"},
    {"symbol": "LICHSGFIN", "name": "LIC Housing Finance", "sector": "Financial"},
    {"symbol": "LLOYDSME", "name": "Lloyds Metals", "sector": "Metals"},
    {"symbol": "LTTS", "name": "L&T Technology Services", "sector": "IT"},
    {"symbol": "LUPIN", "name": "Lupin", "sector": "Pharma"},
    {"symbol": "MANAPPURAM", "name": "Manappuram Finance", "sector": "Financial"},
    {"symbol": "MARICO", "name": "Marico", "sector": "FMCG"},
    {"symbol": "MAXHEALTH", "name": "Max Healthcare", "sector": "Healthcare"},
    {"symbol": "METROPOLIS", "name": "Metropolis Healthcare", "sector": "Healthcare"},
    {"symbol": "MFSL", "name": "Max Financial Services", "sector": "Financial"},
    {"symbol": "MGL", "name": "Mahanagar Gas", "sector": "Energy"},
    {"symbol": "MPHASIS", "name": "Mphasis", "sector": "IT"},
    {"symbol": "MRPL", "name": "MRPL", "sector": "Energy"},
    {"symbol": "MUTHOOTFIN", "name": "Muthoot Finance", "sector": "Financial"},
    {"symbol": "NAM-INDIA", "name": "Nippon Life India AMC", "sector": "Financial"},
    {"symbol": "NATIONALUM", "name": "National Aluminium", "sector": "Metals"},
    {"symbol": "NAUKRI", "name": "Info Edge Naukri", "sector": "IT"},
    {"symbol": "NAVINFLUOR", "name": "Navin Fluorine", "sector": "Chemicals"},
    {"symbol": "NBCC", "name": "NBCC India", "sector": "Infrastructure"},
    {"symbol": "NCC", "name": "NCC Ltd", "sector": "Infrastructure"},
    {"symbol": "NHPC", "name": "NHPC", "sector": "Energy"},
    {"symbol": "NMDC", "name": "NMDC", "sector": "Metals"},
    {"symbol": "OBEROIRLTY", "name": "Oberoi Realty", "sector": "Realty"},
    {"symbol": "OFSS", "name": "Oracle Financial Services", "sector": "IT"},
    {"symbol": "OIL", "name": "Oil India", "sector": "Energy"},
    {"symbol": "PAGEIND", "name": "Page Industries", "sector": "Consumer"},
    {"symbol": "PATANJALI", "name": "Patanjali Foods", "sector": "FMCG"},
    {"symbol": "PERSISTENT", "name": "Persistent Systems", "sector": "IT"},
    {"symbol": "PETRONET", "name": "Petronet LNG", "sector": "Energy"},
    {"symbol": "PFC", "name": "Power Finance Corp", "sector": "Financial"},
    {"symbol": "PFIZER", "name": "Pfizer", "sector": "Pharma"},
    {"symbol": "PGHH", "name": "P&G Hygiene", "sector": "FMCG"},
    {"symbol": "PHOENIXLTD", "name": "Phoenix Mills", "sector": "Realty"},
    {"symbol": "POLYCAB", "name": "Polycab India", "sector": "Capital Goods"},
    {"symbol": "POONAWALLA", "name": "Poonawalla Fincorp", "sector": "Financial"},
    {"symbol": "PRESTIGE", "name": "Prestige Estates", "sector": "Realty"},
    {"symbol": "PVRINOX", "name": "PVR INOX", "sector": "Entertainment"},
    {"symbol": "RADICO", "name": "Radico Khaitan", "sector": "Consumer"},
    {"symbol": "RAIN", "name": "Rain Industries", "sector": "Chemicals"},
    {"symbol": "RAMCOCEM", "name": "Ramco Cements", "sector": "Cement"},
    {"symbol": "RBLBANK", "name": "RBL Bank", "sector": "Banking"},
    {"symbol": "RECLTD", "name": "REC Ltd", "sector": "Financial"},
    {"symbol": "RELAXO", "name": "Relaxo Footwears", "sector": "Consumer"},
    {"symbol": "SAIL", "name": "SAIL", "sector": "Metals"},
    {"symbol": "SBICARD", "name": "SBI Cards", "sector": "Financial"},
    {"symbol": "SHREECEM", "name": "Shree Cement", "sector": "Cement"},
    {"symbol": "SJVN", "name": "SJVN", "sector": "Energy"},
    {"symbol": "SONACOMS", "name": "Sona BLW Precision", "sector": "Auto"},
    {"symbol": "STARHEALTH", "name": "Star Health", "sector": "Insurance"},
    {"symbol": "SUMICHEM", "name": "Sumitomo Chemical", "sector": "Chemicals"},
    {"symbol": "SUNDARMFIN", "name": "Sundaram Finance", "sector": "Financial"},
    {"symbol": "SUNDRMFAST", "name": "Sundram Fasteners", "sector": "Auto"},
    {"symbol": "SUPREMEIND", "name": "Supreme Industries", "sector": "Building Materials"},
    {"symbol": "SYNGENE", "name": "Syngene International", "sector": "Pharma"},
    {"symbol": "TATACHEM", "name": "Tata Chemicals", "sector": "Chemicals"},
    {"symbol": "TATACOMM", "name": "Tata Communications", "sector": "Telecom"},
    {"symbol": "TATAELXSI", "name": "Tata Elxsi", "sector": "IT"},
    {"symbol": "TATAPOWER", "name": "Tata Power", "sector": "Energy"},
    {"symbol": "THERMAX", "name": "Thermax", "sector": "Capital Goods"},
    {"symbol": "TORNTPHARM", "name": "Torrent Pharma", "sector": "Pharma"},
    {"symbol": "TORNTPOWER", "name": "Torrent Power", "sector": "Energy"},
    {"symbol": "TRENT", "name": "Trent", "sector": "Retail"},
    {"symbol": "TRIDENT", "name": "Trident", "sector": "Textiles"},
    {"symbol": "TIINDIA", "name": "Tube Investments", "sector": "Auto"},
    {"symbol": "UNIONBANK", "name": "Union Bank", "sector": "Banking"},
    {"symbol": "UPL", "name": "UPL", "sector": "Chemicals"},
    {"symbol": "VOLTAS", "name": "Voltas", "sector": "Consumer"},
    {"symbol": "WHIRLPOOL", "name": "Whirlpool India", "sector": "Consumer"},
    {"symbol": "ZEEL", "name": "Zee Entertainment", "sector": "Media"},
    {"symbol": "ZYDUSLIFE", "name": "Zydus Lifesciences", "sector": "Pharma"},
]

SECTORS = sorted(list(set(s["sector"] for s in STOCK_LIST)))

NSE_HOLIDAYS_2025 = [
    "2025-01-26", "2025-02-26", "2025-03-14", "2025-03-31",
    "2025-04-10", "2025-04-14", "2025-04-18", "2025-05-01",
    "2025-06-07", "2025-07-06", "2025-08-15", "2025-08-16",
    "2025-09-05", "2025-10-02", "2025-10-20", "2025-10-21",
    "2025-11-05", "2025-11-26", "2025-12-25",
]
